name: news
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  dio: ^5.4.0
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.9
  injector: ^3.0.0
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"
  riverpod_annotation: ^2.3.3
  uuid: ^4.2.2
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.7
  change_app_package_name: ^1.1.0
  custom_lint: ^0.5.7
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.5
  riverpod_generator: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - .env
